services:
  # L'application Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_IMAGE:-keyhome-backend}
    container_name: keyhome-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - keyhome-network
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - APP_ENV=production

  # Le serveur Web (Nginx)
  web:
    image: nginx:alpine
    container_name: keyhome-web
    restart: unless-stopped
    ports:
      - "9090:80" # On utilise 9090 pour sortir de la zone de conflit 808x
    volumes:
      - .:/var/www
      - .docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - keyhome-network

  # La base de données (Postgres + PostGIS)
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: keyhome-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-keyhome}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - keyhome-db-data:/var/lib/postgresql/data
    networks:
      - keyhome-network

  # Cache (Redis)
  redis:
    image: redis:alpine
    container_name: keyhome-redis
    restart: unless-stopped
    networks:
      - keyhome-network

  # Interface de gestion de base de données
  pgadmin:
    image: dpage/pgadmin4
    container_name: keyhome-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - keyhome-network

networks:
  keyhome-network:
    driver: bridge

volumes:
  keyhome-db-data:
    driver: local
