services:
  # L'application Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: immoapp-backend
    container_name: keyhome-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - keyhome-network

  # Le serveur Web (Nginx)
  web:
    image: nginx:alpine
    container_name: keyhome-web
    restart: unless-stopped
    ports:
      - "8082:80" # Changé de 8080 à 8081
    volumes:
      - .:/var/www
      - .docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - keyhome-network

  # La base de données (Postgres + PostGIS)
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: keyhome-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-keyhome}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - keyhome-db-data:/var/lib/postgresql/data
    networks:
      - keyhome-network

  # Cache (Redis)
  redis:
    image: redis:alpine
    container_name: keyhome-redis
    restart: unless-stopped
    networks:
      - keyhome-network

networks:
  keyhome-network:
    driver: bridge

volumes:
  keyhome-db-data:
    driver: local
